### ISSUE TITLE
How to use this for dumping 360 fucked apps?

### ISSUE THREAD

**Issue by Mikesew1320** [maiyao1988/360reverse#1]
Interesting repo but there is nothing thwt explains about it's usage. 

Can u write usage guidr please?

**Comment by maiyao1988** [comment]
those files are only 360 dumped file，not a tools here，want to know how I get it，there are many infomation about unpacking 360 dex file on the Internet。there is a modified Android rom which can do this，you can search youpk on github。

for the hidden so in 360，if you are not interesting in how 360 implement dex shell，this is not important usually。
